<?php $this->headTitle('Event list - Admin area'); ?>
<div class="wrap">
      <div class="full-width">
        <div class="title-page">
        <div class="border-bottom">
          <hgroup class="clearfix">
          <h2><strong>Manage conferences</strong></h2>
          </hgroup>
          </div>
        </div>
        
          <div>List of conferences....</div>
        
      </div>
    </div>
