<div class="wrap">
  <div class="full-width">
    <div class="title-page">
    <div class="border-bottom">
      <hgroup class="clearfix centered-block">
      <h2 class="centered"><strong>Help Us Out!</strong></h2>
      <h3 class="centered">You think that something here needs to be fixed?<br />
        Please let us know and help us improve the platform, thank you!</h3>
      </hgroup>
      </div>
    </div>
 
    <section id="content" class="fl">
    	<form action="<?php echo $this->url('feedback/send')?>" method="post" id="feedback-form">
    	<?php 
    	
    	$elements = $this->form->getElements();
    	foreach($elements as $element) { 
            echo '<div>' . $this->formRow($element) . '</div>' . "\n";
        } 
        
        ?>
    	</form>
    </section>
    <!-- END: content -->
    
   <?php echo $this->rightSideBar(); ?>
    
  </div>
</div>
