    <?php $this->headTitle('Your Simple One Stop for Best Upcoming Conferences') ?>
    <div class="wrap">
      <div class="full-width">
        <div class="title-page">
        <div class="border-bottom">
          <hgroup class="clearfix">
          <h2>About <?php echo $this->controllerDefinedSlug; ?></h2>
          <h3>A standard static page.</h3>
          </hgroup>
          </div>
        </div>
       
      </div>
    </div>
    <!-- END: wrap--> 