<?php $this->headTitle('Your Simple One Stop for Best Upcoming Conferences') ?>
<div class="wrap">
    
        <section id="content" class="fl">
         <div class="conferences clearfix">
            <h2>Our Team</h2>
          Bugs Bunny
         <div class="more"><a href="<?php echo $this->url("application/team-member", array("slug" => "bunny")) ?>" class="bigbutton">View Detail</a></div>
		</div>
		<!-- END: conferences --> 
          
        </section>
        <!-- END: content -->
        
      </div>
</div>
